% Dictionnaire des phonèmes Français.

pron1('b','b').
pron1('b','b').
pron1('d','d').
pron1('d','d').
pron1('f','f').
pron1('f','f').
pron1('g','ɡ').
pron1('g','ɡ').
pron1('c','k').
pron1('q','k').
pron1('k','k').
pron1('k','k').
pron1('l','l').
pron1('l','l').
pron1('m','m').
pron1('m','m').
pron1('n','n').
pron1('n','n').
pron1('p','p').
pron1('p','p').
pron1('r','ʁ').
pron1('s','s').
pron1('e; ','s').
pron1('c','s').
pron1('ç','s').
pron1('t','s').
pron1('s','s').
pron1('t','t').
pron1('t','t').
pron1('v','v').
pron1('w','v').
pron1('v','v').
pron1('s','z').
pron1('z','z').
pron1('z','z').
pron1('j','ʒ').
pron1('g','ʒ').
pron1('j','x').
pron1('i','j').
pron1('y','j').
pron1('o','w').
pron1('o','w').
pron1('w','w').
pron1('w','w').
pron1('u','ɥ').
pron1('a','a').
pron1('a','a').
pron1('â','ɑ').
pron1('a','ɑ').
pron1('é','e').
pron1('e','e').
pron1('è','ɛ').
pron1('e','ɛ').
pron1('e','ɛ').
pron1('e','ɛ').
pron1('ê','ɛː').
pron1('è','ɛː').
pron1('e','ə').
pron1('e','ə').
pron1('i','i').
pron1('î','i').
pron1('y','i').
pron1('o','o').
pron1('ô','o').
pron1('o','ɔ').
pron1('u','ɔ').
pron1('o','ɔ').
pron1('u','y').
pron1('û','y').

% Pron2
pron2('an','ɑ̃').
pron2('in','ɛ̃').
pron2('im','ɛ̃').
pron2('en','ɛ̃').
pron2('uh','ɛ̃').
pron2('un','œ̃').
pron2('um','œ̃').
pron2('on','ɔ̃').
pron2('om','ɔ̃').
pron2('an','ɑ̃').
pron2('am','ɑ̃').
pron2('en','ɑ̃').
pron2('em','ɑ̃').
pron2('ou','u').
pron2('au','o').
pron2('œu','œ').
pron2('eu','œ').
pron2('eu','ø').
pron2('eû','ø').
pron2('ai','ɛː').
pron2('eî','ɛː').
pron2('aî','ɛː').
pron2('ei','ɛː').
pron2('ai','ɛ').
pron2('ou','w').
pron2('ll','j').
pron2('il','j').
pron2('kh','x').
pron2('dj','dʒ').
pron2('ng','ŋ').
pron2('ng','ŋ').
pron2('th','t').
pron2('sh','ʃ').
pron2('ch','ʃ').
pron2('sc','s').
pron2('ss','s').
pron2('rh','ʁ').
pron2('gn','ɲ').
pron2('nn','n').
pron2('mm','m').
pron2('ch','k').
pron2('aï','k').
pron2('qu','k').
pron2('gu','ɡ').
pron2('ph','f').

% Pron3
pron3('ain','ɛ̃').
pron3('aim','ɛ̃').
pron3('ein','ɛ̃').
pron3('eim','ɛ̃').
pron3('ean','ɑ̃').
pron3('aon','ɑ̃').
pron3('eau','o').
pron3('tch','tʃ').
pron3('sch','ʃ').

% Petit problème d'ambiguiter avec 'ent' -> Peut s'entendre de plusieurs manière.
pron3('ent', 'ɑ̃').
pron3('ant', 'ɑ̃').