% Liste des symbole et des phonemes en Français.

phoneme('i','e').
phoneme('i','ea').
phoneme('i','ee').
phoneme('i','ees').
phoneme('i','eo').
phoneme('i','hi').
phoneme('i','hî').
phoneme('i','hie').
phoneme('i','hies').
phoneme('i','his').
phoneme('i','hit').
phoneme('i','hît').
phoneme('i','hy').
phoneme('i','i').
phoneme('i','î').
phoneme('i','ï').
phoneme('i','ict').
phoneme('i','icts').
phoneme('i','id').
phoneme('i','ids').
phoneme('i','ïe').
phoneme('i','ie').
phoneme('i','ient').
phoneme('i','ies').
phoneme('i','ïes').
phoneme('i','ih').
phoneme('i','ii').
phoneme('i','il').
phoneme('i','ils').
phoneme('i','ïs').
phoneme('i','is').
phoneme('i','ît').
phoneme('i','ït').
phoneme('i','it').
phoneme('i','its').
phoneme('i','ix').
phoneme('i','iz').
phoneme('i','u').
phoneme('i','y').
phoneme('i','ye').
phoneme('i','yes').
phoneme('i','yg').
phoneme('i','ys').
phoneme('e','a').
phoneme('e','æ').
phoneme('e','aî').
phoneme('e','aie').
phoneme('e','ay').
phoneme('e','e').
phoneme('e','é').
phoneme('e','ê').
phoneme('e','ë').
phoneme('e','ea').
phoneme('e','ed').
phoneme('e','eds').
phoneme('e','ee').
phoneme('e','ée').
phoneme('e','éent').
phoneme('e','ées').
phoneme('e','ees').
phoneme('e','ef').
phoneme('e','efs').
phoneme('e','eh').
phoneme('e','èh').
phoneme('e','ehe').
phoneme('e','ehes').
phoneme('e','ehs').
phoneme('e','èhs').
phoneme('e','ei').
phoneme('e','ept').
phoneme('e','er').
phoneme('e','ers').
phoneme('e','ës').
phoneme('e','és').
phoneme('e','es').
phoneme('e','et').
phoneme('e','ez').
phoneme('e','ha').
phoneme('e','hai').
phoneme('e','he').
phoneme('e','hé').
phoneme('e','ier').
phoneme('e','iers').
phoneme('e','œ').
phoneme('ɛ','ä').
phoneme('ɛ','a').
phoneme('ɛ','ai').
phoneme('ɛ','aî').
phoneme('ɛ','aid').
phoneme('ɛ','aids').
phoneme('ɛ','aie').
phoneme('ɛ','aient').
phoneme('ɛ','aies').
phoneme('ɛ','ais').
phoneme('ɛ','ait').
phoneme('ɛ','aît').
phoneme('ɛ','aits').
phoneme('ɛ','aix').
phoneme('ɛ','ay').
phoneme('ɛ','aye').
phoneme('ɛ','ayes').
phoneme('ɛ','ays').
phoneme('ɛ','e').
phoneme('ɛ','è').
phoneme('ɛ','ê').
phoneme('ɛ','ë').
phoneme('ɛ','ea').
phoneme('ɛ','ect').
phoneme('ɛ','ects').
phoneme('ɛ','ee').
phoneme('ɛ','ef').
phoneme('ɛ','efs').
phoneme('ɛ','egs').
phoneme('ɛ','eh').
phoneme('ɛ','èh').
phoneme('ɛ','ei').
phoneme('ɛ','eî').
phoneme('ɛ','es').
phoneme('ɛ','ès').
phoneme('ɛ','est').
phoneme('ɛ','êt').
phoneme('ɛ','et').
phoneme('ɛ','ets').
phoneme('ɛ','êts').
phoneme('ɛ','ey').
phoneme('ɛ','eys').
phoneme('ɛ','ez').
phoneme('ɛ','hai').
phoneme('ɛ','haie').
phoneme('ɛ','haies').
phoneme('ɛ','hais').
phoneme('ɛ','hait').
phoneme('ɛ','haits').
phoneme('ɛ','he').
phoneme('ɛ','hè').
phoneme('ɛ','hê').
phoneme('ɛ','hea').
phoneme('ɛ','hee').
phoneme('ɛ','hei').
phoneme('ɛ','œ').
phoneme('a','a').
phoneme('a','à').
phoneme('a','ac').
phoneme('a','ach').
phoneme('a','achs').
phoneme('a','acs').
phoneme('a','act').
phoneme('a','acts').
phoneme('a','ae').
phoneme('a','ah').
phoneme('a','ahs').
phoneme('a','ao').
phoneme('a','ap').
phoneme('a','aps').
phoneme('a','as').
phoneme('a','at').
phoneme('a','ats').
phoneme('a','e').
phoneme('a','ê').
phoneme('a','ha').
phoneme('a','has').
phoneme('a','he').
phoneme('a','i').
phoneme('a','î').
phoneme('a','id').
phoneme('a','ids').
phoneme('a','ie').
phoneme('a','ient').
phoneme('a','ies').
phoneme('a','ig').
phoneme('a','igt').
phoneme('a','igts').
phoneme('a','is').
phoneme('a','it').
phoneme('a','ît').
phoneme('a','its').
phoneme('a','îts').
phoneme('a','ix').
phoneme('a','o').
phoneme('a','u').
phoneme('a','y').
phoneme('a','ye').
phoneme('a','yes').
phoneme('a','ys').
phoneme('ɑ','a').
phoneme('ɑ','â').
phoneme('ɑ','aa').
phoneme('ɑ','acs').
phoneme('ɑ','ah').
phoneme('ɑ','ars').
phoneme('ɑ','as').
phoneme('ɑ','ât').
phoneme('ɑ','âts').
phoneme('ɑ','ats').
phoneme('ɑ','az').
phoneme('ɑ','ha').
phoneme('ɑ','hâ').
phoneme('ɑ','ids').
phoneme('ɑ','is').
phoneme('ɑ','ix').
phoneme('ɔ','a').
phoneme('ɔ','al').
phoneme('ɔ','au').
phoneme('ɔ','aw').
phoneme('ɔ','eo').
phoneme('ɔ','hau').
phoneme('ɔ','ho').
phoneme('ɔ','hô').
phoneme('ɔ','o').
phoneme('ɔ','oa').
phoneme('ɔ','oe').
phoneme('ɔ','oen').
phoneme('ɔ','oi').
phoneme('ɔ','oo').
phoneme('ɔ','ow').
phoneme('ɔ','u').
phoneme('ɔ','ü').
phoneme('o','a').
phoneme('o','ach').
phoneme('o','ao').
phoneme('o','aos').
phoneme('o','au').
phoneme('o','aud').
phoneme('o','auds').
phoneme('o','aul').
phoneme('o','ault').
phoneme('o','aults').
phoneme('o','aulx').
phoneme('o','aus').
phoneme('o','aut').
phoneme('o','auts').
phoneme('o','aux').
phoneme('o','aw').
phoneme('o','eau').
phoneme('o','eaux').
phoneme('o','ha').
phoneme('o','hau').
phoneme('o','haut').
phoneme('o','hauts').
phoneme('o','haw').
phoneme('o','heau').
phoneme('o','ho').
phoneme('o','hô').
phoneme('o','hot').
phoneme('o','hots').
phoneme('o','o').
phoneme('o','ô').
phoneme('o','oa').
phoneme('o','oc').
phoneme('o','ocs').
phoneme('o','ods').
phoneme('o','oh').
phoneme('o','op').
phoneme('o','ops').
phoneme('o','os').
phoneme('o','ot').
phoneme('o','ôt').
phoneme('o','oth').
phoneme('o','oths').
phoneme('o','ôts').
phoneme('o','ots').
phoneme('o','ow').
phoneme('o','ows').
phoneme('o','u').
phoneme('u','aou').
phoneme('u','aoul').
phoneme('u','aouls').
phoneme('u','août').
phoneme('u','aoûts').
phoneme('u','ew').
phoneme('u','ewe').
phoneme('u','ewent').
phoneme('u','ewes').
phoneme('u','ews').
phoneme('u','hoo').
phoneme('u','hou').
phoneme('u','houe').
phoneme('u','houes').
phoneme('u','hout').
phoneme('u','houts').
phoneme('u','houx').
phoneme('u','o').
phoneme('u','oo').
phoneme('u','ou').
phoneme('u','où').
phoneme('u','oû').
phoneme('u','oub').
phoneme('u','oubs').
phoneme('u','ouc').
phoneme('u','oucs').
phoneme('u','oud').
phoneme('u','ouds').
phoneme('u','oue').
phoneme('u','ouent').
phoneme('u','oues').
phoneme('u','oug').
phoneme('u','ougs').
phoneme('u','ouh').
phoneme('u','oûl').
phoneme('u','ouls').
phoneme('u','oûls').
phoneme('u','oult').
phoneme('u','oup').
phoneme('u','oups').
phoneme('u','ous').
phoneme('u','oût').
phoneme('u','out').
phoneme('u','outs').
phoneme('u','oûts').
phoneme('u','oux').
phoneme('u','ow').
phoneme('u','u').
phoneme('u','û').
phoneme('u','ue').
phoneme('u','us').
phoneme('u','uu').
phoneme('y','eu').
phoneme('y','eû').
phoneme('y','eue').
phoneme('y','eues').
phoneme('y','eus').
phoneme('y','eut').
phoneme('y','eût').
phoneme('y','hu').
phoneme('y','hue').
phoneme('y','huent').
phoneme('y','hues').
phoneme('y','hus').
phoneme('y','hut').
phoneme('y','huts').
phoneme('y','u').
phoneme('y','û').
phoneme('y','ud').
phoneme('y','uds').
phoneme('y','uë').
phoneme('y','ue').
phoneme('y','ü').
phoneme('y','üh').
phoneme('y','uent').
phoneme('y','uës').
phoneme('y','ues').
phoneme('y','uh').
phoneme('y','ui').
phoneme('y','ul').
phoneme('y','uls').
phoneme('y','us').
phoneme('y','ut').
phoneme('y','ût').
phoneme('y','uth').
phoneme('y','uths').
phoneme('y','uts').
phoneme('y','ûts').
phoneme('y','ux').
phoneme('ø','eu').
phoneme('ø','eû').
phoneme('ø','eue').
phoneme('ø','eues').
phoneme('ø','euf').
phoneme('ø','euh').
phoneme('ø','euhs').
phoneme('ø','eur').
phoneme('ø','eurs').
phoneme('ø','eus').
phoneme('ø','eut').
phoneme('ø','eux').
phoneme('ø','heu').
phoneme('ø','ö').
phoneme('ø','oeh').
phoneme('ø','œu').
phoneme('ø','œud').
phoneme('ø','œuds').
phoneme('ø','œufs').
phoneme('ø','œux').
phoneme('ø','on').
phoneme('œ','a').
phoneme('œ','e').
phoneme('œ','eu').
phoneme('œ','he').
phoneme('œ','heu').
phoneme('œ','hu').
phoneme('œ','i').
phoneme('œ','o').
phoneme('œ','ö').
phoneme('œ','œ').
phoneme('œ','œu').
phoneme('œ','ou').
phoneme('œ','u').
phoneme('ə','ai').
phoneme('ə','e').
phoneme('ə','ent').
phoneme('ə','es').
phoneme('ə','on').
phoneme('ɛ','aim').
phoneme('ɛ','aims').
phoneme('ɛ','ain').
phoneme('ɛ','ainc').
phoneme('ɛ','aincs').
phoneme('ɛ','aing').
phoneme('ɛ','aings').
phoneme('ɛ','ains').
phoneme('ɛ','aint').
phoneme('ɛ','aints').
phoneme('ɛ','ein').
phoneme('ɛ','eing').
phoneme('ɛ','eings').
phoneme('ɛ','eins').
phoneme('ɛ','eint').
phoneme('ɛ','eints').
phoneme('ɛ','en').
phoneme('ɛ','ens').
phoneme('ɛ','ent').
phoneme('ɛ','hein').
phoneme('ɛ','hen').
phoneme('ɛ','hin').
phoneme('ɛ','im').
phoneme('ɛ','in').
phoneme('ɛ','în').
phoneme('ɛ','ïn').
phoneme('ɛ','inc').
phoneme('ɛ','inct').
phoneme('ɛ','incts').
phoneme('ɛ','ing').
phoneme('ɛ','ings').
phoneme('ɛ','ingt').
phoneme('ɛ','ingts').
phoneme('ɛ','ins').
phoneme('ɛ','int').
phoneme('ɛ','înt').
phoneme('ɛ','ints').
phoneme('ɛ','ym').
phoneme('ɛ','yms').
phoneme('ɛ','yn').
phoneme('ɑ','aans').
phoneme('ɑ','am').
phoneme('ɑ','amp').
phoneme('ɑ','amps').
phoneme('ɑ','ams').
phoneme('ɑ','an').
phoneme('ɑ','anc').
phoneme('ɑ','ancs').
phoneme('ɑ','and').
phoneme('ɑ','ands').
phoneme('ɑ','angs').
phoneme('ɑ','ans').
phoneme('ɑ','ant').
phoneme('ɑ','ants').
phoneme('ɑ','ão').
phoneme('ɑ','aon').
phoneme('ɑ','aons').
phoneme('ɑ','ãos').
phoneme('ɑ','e').
phoneme('ɑ','em').
phoneme('ɑ','emp').
phoneme('ɑ','emps').
phoneme('ɑ','empt').
phoneme('ɑ','empts').
phoneme('ɑ','en').
phoneme('ɑ','end').
phoneme('ɑ','ends').
phoneme('ɑ','eng').
phoneme('ɑ','engs').
phoneme('ɑ','ens').
phoneme('ɑ','ent').
phoneme('ɑ','ents').
phoneme('ɑ','ham').
phoneme('ɑ','han').
phoneme('ɑ','hans').
phoneme('ɑ','hen').
phoneme('ɔ','hon').
phoneme('ɔ','om').
phoneme('ɔ','omb').
phoneme('ɔ','ombs').
phoneme('ɔ','omp').
phoneme('ɔ','omps').
phoneme('ɔ','ompt').
phoneme('ɔ','ompts').
phoneme('ɔ','oms').
phoneme('ɔ','on').
phoneme('ɔ','onc').
phoneme('ɔ','ond').
phoneme('ɔ','onds').
phoneme('ɔ','ong').
phoneme('ɔ','ongs').
phoneme('ɔ','ons').
phoneme('ɔ','ont').
phoneme('ɔ','onts').
phoneme('ɔ','un').
phoneme('ɔ','ung').
phoneme('œ','eun').
phoneme('œ','hum').
phoneme('œ','um').
phoneme('œ','ums').
phoneme('œ','un').
phoneme('œ','uns').
phoneme('œ','unt').
phoneme('œ','unts').
phoneme('j','g').
phoneme('j','gh').
phoneme('j','gui').
phoneme('j','hi').
phoneme('j','hy').
phoneme('j','i').
phoneme('j','ï').
phoneme('j','ïe').
phoneme('j','ïes').
phoneme('j','il').
phoneme('j','ill').
phoneme('j','ille').
phoneme('j','illent').
phoneme('j','illes').
phoneme('j','illi').
phoneme('j','ils').
phoneme('j','ïs').
phoneme('j','j').
phoneme('j','l').
phoneme('j','lh').
phoneme('j','ll').
phoneme('j','lle').
phoneme('j','llent').
phoneme('j','lles').
phoneme('j','lli').
phoneme('j','y').
phoneme('j','ye').
phoneme('j','yent').
phoneme('j','yes').
phoneme('j','ys').
phoneme('j','yer').
phoneme('w','h').
phoneme('w','(rien)').
phoneme('w','ho').
phoneme('w','hou').
phoneme('w','hu').
phoneme('w','o').
phoneme('w','oo').
phoneme('w','ou').
phoneme('w','u').
phoneme('w','w').
phoneme('w','wh').
phoneme('ɥ','hu').
phoneme('ɥ','u').
phoneme('ɥ','yu').
phoneme('p','b').
phoneme('p','p').
phoneme('p','pe').
phoneme('p','pent').
phoneme('p','pes').
phoneme('p','pp').
phoneme('p','ppe').
phoneme('p','ppent').
phoneme('p','ppes').
phoneme('p','ps').
phoneme('t','c').
phoneme('t','d').
phoneme('t','dt').
phoneme('t','pt').
phoneme('t','pte').
phoneme('t','ptent').
phoneme('t','ptes').
phoneme('t','t').
phoneme('t','te').
phoneme('t','tent').
phoneme('t','tes').
phoneme('t','th').
phoneme('t','the').
phoneme('t','thent').
phoneme('t','thes').
phoneme('t','ths').
phoneme('t','tre').
phoneme('t','ts').
phoneme('t','tt').
phoneme('t','tte').
phoneme('t','ttent').
phoneme('t','ttes').
phoneme('t','tts').
phoneme('k','c').
phoneme('k','cc').
phoneme('k','cch').
phoneme('k','ccu').
phoneme('k','ch').
phoneme('k','chs').
phoneme('k','ck').
phoneme('k','cke').
phoneme('k','ckent').
phoneme('k','ckes').
phoneme('k','cks').
phoneme('k','cqu').
phoneme('k','cque').
phoneme('k','cques').
phoneme('k','cs').
phoneme('k','cu').
phoneme('k','g').
phoneme('k','gs').
phoneme('k','k').
phoneme('k','ke').
phoneme('k','kes').
phoneme('k','kg').
phoneme('k','kh').
phoneme('k','khe').
phoneme('k','khes').
phoneme('k','khs').
phoneme('k','kk').
phoneme('k','ks').
phoneme('k','q').
phoneme('k','qs').
phoneme('k','qu').
phoneme('k','que').
phoneme('k','quent').
phoneme('k','ques').
phoneme('k','x').
phoneme('b','b').
phoneme('b','bb').
phoneme('b','bbe').
phoneme('b','bbes').
phoneme('b','be').
phoneme('b','bent').
phoneme('b','bes').
phoneme('b','bs').
phoneme('d','d').
phoneme('d','dd').
phoneme('d','ddh').
phoneme('d','de').
phoneme('d','dent').
phoneme('d','des').
phoneme('d','dh').
phoneme('d','ds').
phoneme('d','g').
phoneme('d','z').
phoneme('ɡ','c').
phoneme('ɡ','g').
phoneme('ɡ','gg').
phoneme('ɡ','gh').
phoneme('ɡ','ghe').
phoneme('ɡ','ghs').
phoneme('ɡ','gs').
phoneme('ɡ','gu').
phoneme('ɡ','gue').
phoneme('ɡ','guent').
phoneme('ɡ','gues').
phoneme('f','f').
phoneme('f','fe').
phoneme('f','fent').
phoneme('f','fes').
phoneme('f','ff').
phoneme('f','ffe').
phoneme('f','ffent').
phoneme('f','ffes').
phoneme('f','ffs').
phoneme('f','fs').
phoneme('f','gh').
phoneme('f','ghs').
phoneme('f','ph').
phoneme('f','phe').
phoneme('f','phent').
phoneme('f','phes').
phoneme('f','phs').
phoneme('f','v').
phoneme('f','ve').
phoneme('f','vs').
phoneme('s','ç').
phoneme('s','c').
phoneme('s','cc').
phoneme('s','ce').
phoneme('s','cent').
phoneme('s','ces').
phoneme('s','ls').
phoneme('s','s').
phoneme('s','sc').
phoneme('s','sç').
phoneme('s','sce').
phoneme('s','scent').
phoneme('s','sces').
phoneme('s','se').
phoneme('s','sent').
phoneme('s','ses').
phoneme('s','ss').
phoneme('s','sse').
phoneme('s','ssent').
phoneme('s','sses').
phoneme('s','sth').
phoneme('s','t').
phoneme('s','th').
phoneme('s','ts').
phoneme('s','x').
phoneme('s','z').
phoneme('ʃ','c').
phoneme('ʃ','ch').
phoneme('ʃ','che').
phoneme('ʃ','chent').
phoneme('ʃ','ches').
phoneme('ʃ','chs').
phoneme('ʃ','ci').
phoneme('ʃ','j').
phoneme('ʃ','je').
phoneme('ʃ','jes').
phoneme('ʃ','s').
phoneme('ʃ','sc').
phoneme('ʃ','sch').
phoneme('ʃ','sche').
phoneme('ʃ','schent').
phoneme('ʃ','sches').
phoneme('ʃ','schs').
phoneme('ʃ','sh').
phoneme('ʃ','she').
phoneme('ʃ','shent').
phoneme('ʃ','shes').
phoneme('ʃ','shs').
phoneme('ʃ','zsch').
phoneme('v','v').
phoneme('v','ve').
phoneme('v','vent').
phoneme('v','ves').
phoneme('v','vs').
phoneme('v','w').
phoneme('z','s').
phoneme('z','se').
phoneme('z','sent').
phoneme('z','ses').
phoneme('z','si').
phoneme('z','x').
phoneme('z','z').
phoneme('z','ze').
phoneme('z','zent').
phoneme('z','zes').
phoneme('z','zz').
phoneme('ʒ','g').
phoneme('ʒ','ge').
phoneme('ʒ','gent').
phoneme('ʒ','ges').
phoneme('ʒ','gg').
phoneme('ʒ','j').
phoneme('ʒ','je').
phoneme('ʒ','jent').
phoneme('ʒ','jes').
phoneme('ʒ','js').
phoneme('l','gl').
phoneme('l','l').
phoneme('l','ld').
phoneme('l','le').
phoneme('l','lent').
phoneme('l','les').
phoneme('l','ll').
phoneme('l','lle').
phoneme('l','llent').
phoneme('l','lles').
phoneme('l','lls').
phoneme('l','lp').
phoneme('l','ls').
phoneme('ʁ','j').
phoneme('ʁ','r').
phoneme('ʁ','rc').
phoneme('ʁ','rcs').
phoneme('ʁ','rd').
phoneme('ʁ','rds').
phoneme('ʁ','re').
phoneme('ʁ','rent').
phoneme('ʁ','res').
phoneme('ʁ','rf').
phoneme('ʁ','rfs').
phoneme('ʁ','rg').
phoneme('ʁ','rgs').
phoneme('ʁ','rh').
phoneme('ʁ','rp').
phoneme('ʁ','rps').
phoneme('ʁ','rr').
phoneme('ʁ','rre').
phoneme('ʁ','rrent').
phoneme('ʁ','rres').
phoneme('ʁ','rrh').
phoneme('ʁ','rrhe').
phoneme('ʁ','rrhes').
phoneme('ʁ','rrs').
phoneme('ʁ','rs').
phoneme('ʁ','rt').
phoneme('ʁ','rts').
phoneme('ʁ','wr').
phoneme('m','m').
phoneme('m','me').
phoneme('m','ment').
phoneme('m','mes').
phoneme('m','mm').
phoneme('m','mme').
phoneme('m','mment').
phoneme('m','mmes').
phoneme('m','mms').
phoneme('m','ms').
phoneme('n','kn').
phoneme('n','mn').
phoneme('n','mne').
phoneme('n','mnent').
phoneme('n','mnes').
phoneme('n','n').
phoneme('n','ne').
phoneme('n','ned').
phoneme('n','nent').
phoneme('n','nes').
phoneme('n','nn').
phoneme('n','nne').
phoneme('n','nnent').
phoneme('n','nnes').
phoneme('n','nns').
phoneme('n','ns').
phoneme('ɲ','gn').
phoneme('ɲ','gne').
phoneme('ɲ','gnent').
phoneme('ɲ','gnes').
phoneme('ɲ','gni').
phoneme('ɲ','ñ').
phoneme('h','h').
phoneme('ŋ','n').
phoneme('ŋ','ng').
phoneme('x','ch').
phoneme('x','chs').
phoneme('x','j').
phoneme('x','kh').
